/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

const documents = {
    "#graphql\n  query GetSum {\n    sum {\n      id\n      value\n    }\n  }\n": types.GetSumDocument,
    "#graphql\n  query GetNumber($id: String!) {\n    number(id: $id) {\n      id\n      value\n    }\n  }\n": types.GetNumberDocument,
    "#graphql\n  mutation SaveNumbers($input: String!) {\n    saveNumbers(input: $input) {\n      numbers {\n        id\n        value\n      }\n    }\n  }\n": types.SaveNumbersDocument,
    "#graphql\n  mutation Reset {\n    reset\n  }\n": types.ResetDocument,
    "#graphql\n  query GetExpenses {\n    employee {\n      id\n      reports {\n        id\n        expenses {\n          id\n        }\n      }\n    }\n  }\n": types.GetExpensesDocument,
    "#graphql\n  query GetRacoonReport(\n    $includeName: Boolean!,\n    $includeTotalAmount: Boolean!,\n    $includeExceptions: Boolean!,\n    $includeEntries: Boolean!\n  ) {\n    racoon {\n      report {\n        id\n        name @include(if: $includeName)\n        totalAmount @include(if: $includeTotalAmount)\n        exceptions @include(if: $includeExceptions)\n        entries @include(if: $includeEntries) {\n          id\n          amount\n          receipt\n        }\n      }\n    }\n  }\n": types.GetRacoonReportDocument,
    "#graphql\n  query GetRacoonEntry(\n    $id: String!,\n    $includeAmount: Boolean!,\n    $includeReceipt: Boolean!,\n  ) {\n    racoon {\n      entry(id: $id) {\n        id\n        amount @include(if: $includeAmount)\n        receipt @include(if: $includeReceipt)\n      }\n    }\n  }\n": types.GetRacoonEntryDocument,
    "#graphql\n  mutation UpdateRacoonEntryAmount($id: String!) {\n    racoonMutation {\n      updateEntryAmount(id: $id) {\n        ok\n      }\n    }\n  }\n": types.UpdateRacoonEntryAmountDocument,
    "#graphql\n  mutation UpdateRacoonEntryReceipt($id: String!) {\n    racoonMutation {\n      updateEntryReceipt(id: $id) {\n        ok\n      }\n    }\n  }\n": types.UpdateRacoonEntryReceiptDocument,
};

export function graphql(source: "#graphql\n  query GetSum {\n    sum {\n      id\n      value\n    }\n  }\n"): (typeof documents)["#graphql\n  query GetSum {\n    sum {\n      id\n      value\n    }\n  }\n"];
export function graphql(source: "#graphql\n  query GetNumber($id: String!) {\n    number(id: $id) {\n      id\n      value\n    }\n  }\n"): (typeof documents)["#graphql\n  query GetNumber($id: String!) {\n    number(id: $id) {\n      id\n      value\n    }\n  }\n"];
export function graphql(source: "#graphql\n  mutation SaveNumbers($input: String!) {\n    saveNumbers(input: $input) {\n      numbers {\n        id\n        value\n      }\n    }\n  }\n"): (typeof documents)["#graphql\n  mutation SaveNumbers($input: String!) {\n    saveNumbers(input: $input) {\n      numbers {\n        id\n        value\n      }\n    }\n  }\n"];
export function graphql(source: "#graphql\n  mutation Reset {\n    reset\n  }\n"): (typeof documents)["#graphql\n  mutation Reset {\n    reset\n  }\n"];
export function graphql(source: "#graphql\n  query GetExpenses {\n    employee {\n      id\n      reports {\n        id\n        expenses {\n          id\n        }\n      }\n    }\n  }\n"): (typeof documents)["#graphql\n  query GetExpenses {\n    employee {\n      id\n      reports {\n        id\n        expenses {\n          id\n        }\n      }\n    }\n  }\n"];
export function graphql(source: "#graphql\n  query GetRacoonReport(\n    $includeName: Boolean!,\n    $includeTotalAmount: Boolean!,\n    $includeExceptions: Boolean!,\n    $includeEntries: Boolean!\n  ) {\n    racoon {\n      report {\n        id\n        name @include(if: $includeName)\n        totalAmount @include(if: $includeTotalAmount)\n        exceptions @include(if: $includeExceptions)\n        entries @include(if: $includeEntries) {\n          id\n          amount\n          receipt\n        }\n      }\n    }\n  }\n"): (typeof documents)["#graphql\n  query GetRacoonReport(\n    $includeName: Boolean!,\n    $includeTotalAmount: Boolean!,\n    $includeExceptions: Boolean!,\n    $includeEntries: Boolean!\n  ) {\n    racoon {\n      report {\n        id\n        name @include(if: $includeName)\n        totalAmount @include(if: $includeTotalAmount)\n        exceptions @include(if: $includeExceptions)\n        entries @include(if: $includeEntries) {\n          id\n          amount\n          receipt\n        }\n      }\n    }\n  }\n"];
export function graphql(source: "#graphql\n  query GetRacoonEntry(\n    $id: String!,\n    $includeAmount: Boolean!,\n    $includeReceipt: Boolean!,\n  ) {\n    racoon {\n      entry(id: $id) {\n        id\n        amount @include(if: $includeAmount)\n        receipt @include(if: $includeReceipt)\n      }\n    }\n  }\n"): (typeof documents)["#graphql\n  query GetRacoonEntry(\n    $id: String!,\n    $includeAmount: Boolean!,\n    $includeReceipt: Boolean!,\n  ) {\n    racoon {\n      entry(id: $id) {\n        id\n        amount @include(if: $includeAmount)\n        receipt @include(if: $includeReceipt)\n      }\n    }\n  }\n"];
export function graphql(source: "#graphql\n  mutation UpdateRacoonEntryAmount($id: String!) {\n    racoonMutation {\n      updateEntryAmount(id: $id) {\n        ok\n      }\n    }\n  }\n"): (typeof documents)["#graphql\n  mutation UpdateRacoonEntryAmount($id: String!) {\n    racoonMutation {\n      updateEntryAmount(id: $id) {\n        ok\n      }\n    }\n  }\n"];
export function graphql(source: "#graphql\n  mutation UpdateRacoonEntryReceipt($id: String!) {\n    racoonMutation {\n      updateEntryReceipt(id: $id) {\n        ok\n      }\n    }\n  }\n"): (typeof documents)["#graphql\n  mutation UpdateRacoonEntryReceipt($id: String!) {\n    racoonMutation {\n      updateEntryReceipt(id: $id) {\n        ok\n      }\n    }\n  }\n"];

export function graphql(source: string): unknown;
export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;